### ISSUE TITLE
Use CONDA_PREFIX instead of CONDA_DEFAULT_ENV to set paths

### ISSUE THREAD

**Issue by lpinner** [gqmelo/exec-wrappers#10]
In my conda environment CONDA_DEFAULT_ENV is a basename, not a full path so the scripts that exec-wrappers generated 1. do not use absolute paths and 2. are created relative to the directory that `conda install -c gqmelo conda-wrappers=0.1.0` was called from.

In addition, the CONDA_PREFIX environment variable (which is an absolute path to the env dir) does not get set, so scripts that use it (I have some in activate.d and deactivate.d) do not work correctly.

A quick example:

C:\Temp\testwrappers>activate.bat py27

(py27) C:\Temp\testwrappers>dir /B

(py27) C:\Temp\testwrappers>set conda
CONDA_DEFAULT_ENV=py27
CONDA_ENVS_PATH=C:\conda
CONDA_PREFIX=C:\conda\py27
CONDA_PS1_BACKUP=$P$G

(py27) C:\Temp\testwrappers>conda install -c gqmelo conda-wrappers=0.1.0
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .............
Solving package specifications: ..........

Package plan for installation in environment C:\conda\py27:

The following NEW packages will be INSTALLED:

    conda-wrappers: 0.1.0-py27_0 gqmelo
    exec-wrappers:  0.1.0-py27_0 gqmelo

Proceed ([y]/n)?

Linking packages ...
Creating wrappers from py27\Library\bin to py27\Scripts\wrappers\conda   |  50%
Creating wrappers from py27\Scripts to py27\Scripts\wrappers\conda
Creating wrappers from py27 to py27\Scripts\wrappers\conda
[      COMPLETE      ]|##################################################| 100%

(py27) C:\Temp\testwrappers>dir /B %CONDA_PREFIX%\Scripts\wrappers
File Not Found

(py27) C:\Temp\testwrappers>dir /B
py27

**Comment by gqmelo** [comment]
Hi @lpinner, thanks for reporting it.

Could you tell me what version of conda you are using (```conda list conda```)?

I suppose it is a very old version as I never saw this ```CONDA_PREFIX``` variable.
Since I started using conda a lot has changed on activate/deactivate, but at least on Windows, ```CONDA_DEFAULT_ENV``` always pointed to the activated env absolute path

**Comment by gqmelo** [comment]
Ok, actually you must be with the latest version.
Apparently they changed again the variables set by the activate script. They removed **CONDA_ENV_PATH**, changed **CONDA_DEFAULT_ENV** to be the name again, and introduced **CONDA_PREFIX**.

**Comment by lpinner** [comment]
Hi @gqmelo 

> conda list conda
# packages in environment at Miniconda3:
#
Using Anaconda Cloud api site https://api.anaconda.org
conda                     4.1.11                   py35_0
anaconda-client           1.5.0                    py35_0    conda-forge
conda-env                 2.5.2                    py35_0    conda-forge

**Comment by gqmelo** [comment]
Thanks, I've found out that they changed the environment variables again. Please see my comment on https://github.com/gqmelo/exec-wrappers/issues/11

**Comment by gqmelo** [comment]
Sorry for the delay, this have been fixed by https://github.com/gqmelo/exec-wrappers/commit/5e264b0b6fe34635adba2390809177b7ecae6d64 and already released in PyPI. It should be available in conda-forge soon
