### ISSUE TITLE
Add support for Python 3

### ISSUE THREAD

**Issue by lpinner** [gqmelo/exec-wrappers#11]
C:\Temp\testwrappers>activate.bat py35

(py35) C:\Temp\testwrappers>python -V
Python 3.5.2

(py35) C:\Temp\testwrappers>conda install  -y -c gqmelo conda-wrappers=0.1.0
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .............
Solving package specifications: ....

The following specifications were found to be in conflict:
  - conda-wrappers 0.1.0*
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

(py35) C:\Temp\testwrappers>conda install -c gqmelo exec-wrappers=0.1.0
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .............
Solving package specifications: ....

The following specifications were found to be in conflict:
  - exec-wrappers 0.1.0*
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

**Comment by gqmelo** [comment]
Sorry, as I did not receive any feedback by the time I announced the package, I have been updating it only on **PyPI**.
It works fine with python3, I just need to generate the conda packages.

I'll do that as soon as possible

**Comment by gqmelo** [comment]
I opened a [PR on conda-forge](https://github.com/conda-forge/staged-recipes/pull/1185)

As soon as they merge, the packages should be available on conda-forge channel

**Comment by lpinner** [comment]
Thanks @gqmelo

**Comment by gqmelo** [comment]
I've got to publish ```exec-wrappers``` on conda forge, but the package ```conda-wrappers`` is still [under some discussion](https://github.com/conda-forge/staged-recipes/pull/1205), so it may take a while until it is published.

But all ```conda-wrappers``` does is execute the command provided by ```exec-wrappers```. So if you need it, you can just run:

```batch
activate my-env
conda install -c conda-forge exec-wrappers
create-wrappers -t conda --conda-env-dir %CONDA_PREFIX% -d %CONDA_PREFIX%\Scripts\wrappers\conda -b %CONDA_PREFIX%
create-wrappers -t conda --conda-env-dir %CONDA_PREFIX% -d %CONDA_PREFIX%\Scripts\wrappers\conda -b %CONDA_PREFIX%\Library\bin
create-wrappers -t conda --conda-env-dir %CONDA_PREFIX% -d %CONDA_PREFIX%\Scripts\wrappers\conda -b %CONDA_PREFIX%\Scripts
```

**Comment by gqmelo** [comment]
Sorry for the delay, but the ```conda-wrappers``` recipe was finally merged to conda-forge:

https://github.com/conda-forge/conda-wrappers-feedstock

You can now install it with ```conda install -c conda-forge conda-wrappers```
