### ISSUE TITLE
use exec ?

### ISSUE THREAD

**Issue by neok-m4700** [gqmelo/exec-wrappers#14]
thanks for this useful tool !

sh/bash does not forward signals to the launched processes, so for example when I wrap python and use this wrapper, sending SIGTERM or SIGKILL is not intercepted by the python interpreter ...

a solution would be to use `exec`, which replaces the current shell with the process to be executed ...

Would this be feasible and is it a good idea to use ?

e.g. what works right now:

**python**
```bash
#!/bin/sh
exec <SOME_CONDA_ENV>/bin/wrappers/conda/run-in python "$@"
```

**run-in**
```bash
#!/bin/bash

run_activate_scripts() {
    ACTIVATE_D="$1"
    if [[ -d "$ACTIVATE_D" ]]; then
        for f in $(find "$ACTIVATE_D" -name "*.sh"); do source "$f"; done
    fi
}

export CONDA_PREFIX=<CONDA_ROOT>
export CONDA_DEFAULT_ENV="py3"
export CONDA_ENV_PATH="$CONDA_PREFIX"
export CONDA_PATH_BACKUP="$PATH"
export CONDA_PS1_BACKUP="$PS1"

export PATH="$CONDA_PREFIX/bin:$PATH"
run_activate_scripts "$CONDA_PREFIX/etc/conda/activate.d" &&
exec "$@"
```

**Comment by gqmelo** [comment]
Thanks, I wanted to do that a long time ago and forgot. Actually exec should be used from the beginning, don't know why I didn't.

I'll take some time to make a new release (hopefully not more than one week) as I'd like to improve some things before. 

And glad to see this is useful for somebody else!
