### ISSUE TITLE
No running activate scripts when using ubuntu 16.04, bash 4.3.48, find 4.7.0 

### ISSUE THREAD

**Issue by prusse-martin** [gqmelo/exec-wrappers#27]
Recently installing `conda-wrappers` the generated `run-in` file did not properly execute the activation scripts.
Note that I was also using `conda-devenv` and it relies in the activation scripts to set up environment variables.

After a bit of tinkering I was able to edit the `run-in` script to execute the activation scripts by changing [`while IFS= read -r -d '' f; do`](https://github.com/gqmelo/exec-wrappers/blob/e876ad39128edcf155deeb248c27bff19dbaa7ad/exec_wrappers/templates/conda/run-in#L6) to `while IFS= read -r f; do`.

**Comment by gqmelo** [comment]
Thanks for pointing it out.

This change was done following this recommendation: https://github.com/koalaman/shellcheck/wiki/SC2044

But it is actually missing the `-print0` argument to find. That is why removing the delimiter works. I'll try to take a better look later.
