### ISSUE TITLE
Expose full path of wrapper

### ISSUE THREAD

**Issue by frabar666** [gqmelo/exec-wrappers#29]
First off, thanks for this project! It is very useful, I use it to setup the environment for bindings to Java and native libs.

I have a Python script running in a wrapped interpreter. It spawns another Python script, which needs to run in the same wrapped interpreter.  
However `sys.executable` is the path of the actual Python binary, not the path of the wrapper. I'd like to avoid hard-coding the wrapper's path, especially since it is platform-dependent.

Did I miss a simple way to get the full path of the wrapper that started the current process?  
If not, could an environment variable be added by wrappers (something like `EXEC_WRAPPERS_EXECUTABLE`)?

**Comment by gqmelo** [comment]
Thanks for the interest.

What kind of wrappers are you using, conda?
I'd like to understand why using the same executable would not be enough in this case.

Normally on the first script I would just do something like this:

```python
output = subprocess.check_output([shutil.which("python"), script_path])
```

And this has the advantage of not making your first script dependent on any wrapper. It just uses whatever `python` is on the `PATH`.

**Comment by frabar666** [comment]
I didn't realize activation scripts were "just" setting environment variables (yes, I'm using conda), so new processes inherit them.
Thanks
